app:
  name: "web_app"
  mode: "dev"
  port: 8080
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "web"
  max_open_connes: "20"
  max_idle_conns: "10"
redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  PoolSize: 100
